server:
  port: 8080
  servlet:
    context-path: /identity_service

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DBMS_CONNECTION}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "JZ2kFUePn6qXsPg4MqMFJHerENW+fmcOo7z+3xvXUlavnl/0iP5TrdH7ev/sbSxK"
  valid-duration: 3600 #in seconds
  refreshable-duration: 4000 #in seconds